# Generated by Django 5.0 on 2024-01-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_slug_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image_url',
            new_name='url',
        ),
    ]
