# Generated by Django 5.0 on 2024-01-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productline',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
