# Generated by Django 5.0 on 2024-01-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productline_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productline',
            name='is_active',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
