# Generated by Django 5.0 on 2024-01-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_productline_is_active_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productline',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
